version: "3.11"

services:
  app:
    build: .
    container_name: llm-metrics-lab
    ports:
      - "8000:8000"
    ulimits:
      nofile:
        soft: 100000
        hard: 100000
    command: python main.py

